version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install
  
  pre_build:
    commands:
      - echo "Ejecutando tests..."
      - npm test
  
  build:
    commands:
      - echo "Build completado"
      - echo "Empaquetando Lambda..."
      - cd src && zip -r ../function.zip . && cd ..
      - echo "Actualizando función Lambda..."
      - aws lambda update-function-code --function-name DevOpsDemoFunction --zip-file fileb://function.zip --region us-east-1
      - echo "Esperando actualización..."
      - aws lambda wait function-updated --function-name DevOpsDemoFunction --region us-east-1
      - echo "✅ Lambda actualizada exitosamente"

artifacts:
  files:
    - function.zip
  name: BuildArtifact
