version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install
      - pip3 install aws-sam-cli
  
  pre_build:
    commands:
      - echo "Ejecutando tests..."
      - npm test
  
  build:
    commands:
      - echo "Build completado"
      - echo "Empaquetando con SAM..."
      - sam package --template-file template.yml --s3-bucket devops-demo-pipeline-artifacts-030901817847 --output-template-file packaged.yml

artifacts:
  files:
    - packaged.yml
  name: BuildArtifact
